_BASE_: [
  '../datasets/travel_card_voc.yml',
  '../runtime.yml',
  '_base_/optimizer_40e.yml',
  '_base_/yolov3_travel_card_v1.yml',
  '_base_/yolov3_reader.yml',
]
pretrain_weights: https://paddledet.bj.bcebos.com/models/yolov3_mobilenet_v1_270e_coco.pdparams
weights: output/yolov3_mobilenet_v1_travel_card/model_final

YOLOv3Loss:
  ignore_thresh: 0.7
  label_smooth: true
