metric: VOC
map_type: integral
num_classes: 1

TrainDataset:
  !VOCDataSet
    dataset_dir: F:/paddlex_workspace/datasets/xingchengka_voc
    anno_path: train.txt
    label_list: label_list.txt
    data_fields: ['image', 'gt_bbox', 'gt_class', 'difficult']

EvalDataset:
  !VOCDataSet
    dataset_dir: F:/paddlex_workspace/datasets/xingchengka_voc
    anno_path: valid.txt
    label_list: label_list.txt
    data_fields: ['image', 'gt_bbox', 'gt_class', 'difficult']

TestDataset:
  !ImageFolder
    anno_path: F:/paddlex_workspace/datasets/xingchengka_voc/label_list.txt
